### PR TITLE
Implement overline in Rust

### PR DESCRIPTION
**Pull request by dabreegster**
This has a long way to go, but initial results on a large input:
```
Reading and deserializing cycle_routes_london.geojson
... took 10.795275234s
Running overline on 125317 line-strings
... took 11.485326553s
Aggregating properties on 100230 grouped line-strings
... took 1.990547542s
Writing to output.geojson
... took 877.395391ms
```

Outstanding tasks:

- [x] Add a CLI
- [ ] Improve performance (parallelize, reconsider the conversion to `geo`, check parsing and writing)
- [ ] Come up with a simple way of sanely viewing the output to manually validate. geojson.io and similar aren't good for spotting adjacent line-strings; probably make a custom Leaflet style
- [ ] Optionally split when some property (an OSM ID) changes
- [ ] Ignore direction (optionally?)
- [ ] Split line segments when needed
- [ ] Write a bunch of tests
- [ ] Validate to the R implementation's output, and compare performance

### CODE REVIEW

**Comment by dabreegster** [comment]
What're the ways to aggregate/deal with properties? So far:

```
enum Aggregation {
    /// Copy the value of this property from any input feature containing it. If the property
    /// differs among the input, it's undefined which value will be used.
    KeepAny,
    /// Sum this property as a floating point.
    SumFloat,
}
```

Average/mean is also used, right? We could also have something to collect all unique values into an array, if that's ever used

**Comment by Robinlovelace** [comment]
Sum, mean, first, last. At some point "the value associated with the longest section of linestring that fed into the segment"

**Comment by Robinlovelace** [comment]
Max, min, and x percentile (e.g. 85% percentile speeds) could be useful one day.

**Comment by Robinlovelace** [comment]
`min` and `max` of numeric, yes. `first` can just mean the first appearance in the order that the input is read-in so kind of random.

**Comment by dabreegster** [comment]
Open `viewer.html` from the latest commit in a browser, load an output geojson file (from the new or old overline implementation, doesn't matter). It uses line thickness to display numeric properties. Think this'll work for manually inspecting test output?

**Comment by dabreegster** [comment]
Merging now and adding an issue for all the half-done work mentioned earlier

**Pull request merged**
